name: Python CI Pipeline

on:
  push:
    branches:
      - kernelridge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show repo structure
        run: |
          pwd
          ls -R


