name: Python CI Pipeline

on:
  push:
    branches:
      - kernelridge

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Debug: Show repo structure (optional, helps verify file paths)
      - name: Debug - Show repo structure
        run: |
          pwd
          ls -R

      # Step 5: Run Decision Tree training
      - name: Run Decision Tree Model (train.py)
        run: python train.py

      # Step 6: Run Kernel Ridge training
      - name: Run Kernel Ridge Model (train2.py)
        run: python train2.py


